### ISSUE TITLE
Better websecure?

### ISSUE THREAD

**Issue by hoelger** [scafer/traefik-duckdns-letsencrypt#1]
I had a hard time to get this running, but for me it only worked when using `WEB_ENTRYPOINT=websecure`. Maybe you can change this? I only found this tiny change by chance, comparing it with other tutorials.

As far as I understand it `web` means `http` and `port 80` whereas `websecure` means `https` and `port 443`

I also tried with  `TLS_ENABLED=false` and `WEB_ENTRYPOINT=web` but don't get it running. 

I'm new to traefik and all this. So very probable that I miss some building blocks.

**Comment by hoelger** [comment]
Sorry if this sounded frustrated. I'm very thankful for everyone that uploads their code! And your tutorial is the first one I tried and used with duckdns integrated :)

**For people in the startup phase:**

The other tutorial that worked for me is this one: https://medium.com/@svenvanginkel/setting-up-traefik-v3-in-docker-0c0559a696f1
(here I compared the code and by this one I got yours running.)

Also there you have some typos, so be aware:
```
networks:  - frontend # has to be 'proxy' 
docker volume rm treafik # -> traefik-certs
```

**Comment by scafer** [comment]
Hi @hoelger,

First of all, thanks for taking the time to report the issue.
I will update it and fix some minor issues in the readme file.

Yes, you are right about the web and websecure assumptions.
And as you mentioned, it should be fixed by changing the `WEB_ENTRYPOINT=websecure`.
