### ISSUE TITLE
Cannot move /etc/letsencrypt

### ISSUE THREAD

**Issue by hoelger** [scafer/traefik-duckdns-letsencrypt#2]
When I move the volume path `"/etc/letsencrypt:/letsencrypt"` to somewhere else let's say `"~/letsencrypt:/letsencrypt"` then everything breaks, and does not work anymore.

I notice that in the `/etc/letsencrypt` folder there is the output from when I ran `certbot` before, that's my guess why it was working previously. So for me it looks like you need the certificates beforehand, and I'm unsure if the `dnschallenge.provider=duckdns` and `DUCKDNS_TOKEN` actually do something?

**Comment by scafer** [comment]
Hi @hoelger,

I haven't had a chance to look at the other issue you created. But regarding this one, you don't need to do anything before running the command, the folder content is automatically created and managed by traefik.
These environment variables should be all you need.

Anyway, let me check, as something might have changed in the meantime.

**Comment by scafer** [comment]
Btw, Traefik takes a few minutes to run the SSL Challenge, so it may take a while to retrieve the certificates the first time you run it.

**Comment by scafer** [comment]
@hoelger I was able to get it to work by adding the ACME_EMAIL, DOMAIN and DUCKDNS_TOKEN values and changing WEB_ENTRYPOINT to websecure.

Have you renamed the example.env to .env? I noticed that the command on the readme is wrong, it should be:
`mv example.env .env`

Does Traefik container throw any particular error? As I said, it can take some time to generate the certificate.

If you're having trouble, we can have a call to fix it!

**Comment by hoelger** [comment]
Dear @scafer, thanks for the quick response in the middle of the night. 

I didn't use the `.env` file but just directly filled the docker-compose.yml with the values.

I'm not sure why it doesn't work for me. The log output doesn't indicate errors either.

One thing did a little trick for me: "Each router that is supposed to use the resolver must reference it." After adding `- traefik.http.routers.whoami.tls.certresolver=myresolver` now I always see, how the challenge is executed. Takes about one minute or two. But in my case, any challenge (dns or http or tls) still fails.

Here are the logs:
[log_0.txt](https://github.com/user-attachments/files/15934335/log_0.txt)
[log_1_dnschallenge_timelimit.txt](https://github.com/user-attachments/files/15934336/log_1_dnschallenge_timelimit.txt)
[log_2_tlschallenge.txt](https://github.com/user-attachments/files/15934337/log_2_tlschallenge.txt)

I'm so confused, how did I generate this one working `acme.json` in the first place? :D
Thanks for your offer! Would be lovely if we could have a look together on it some time next week :)

**Comment by scafer** [comment]
Sorry for the delay.
Have you managed to fix it? If not, when would you like to have a look?

**Comment by scafer** [comment]
Feel free to reopen it if the error persists!

**Comment by hoelger** [comment]
Dear Sandro,
Sorry for my late reply, I was not working on this project since my last post. I'll continue tomorrow + Friday. Would you have spontaneously time to look into the code some time tomorrow evening?

**Comment by scafer** [comment]
I @hoelger , we can do it today until 17:00 Lisbon time or if you prefer Monday during the day

**Comment by hoelger** [comment]
That would be great! Can we do 3pm Lisbon / 4pm Berlin? Does skype work for you? My skype handle is `ballin-hoelger`.

**Comment by scafer** [comment]
Yes, I will add you.
