### ISSUE TITLE
Unable to obtain ACME certificate.

### ISSUE THREAD

**Issue by Willdrick** [scafer/traefik-duckdns-letsencrypt#4]
I'm sure I'm doing something wrong, but this looks so simple I'm stumped on how I could screw this up.

I set up this via Portainer, following the guidelines completed the ENV fields required.

After deploying the stack, I can access whoami but Firefox shows me a self-signed cert warning. Looking at Traefik logs I see

```
time="2024-07-01T17:39:27Z" level=info msg="Configuration loaded from flags."

time="2024-07-01T17:41:55Z" level=error msg="Unable to obtain ACME certificate for domains \"somedomain.duckdns.org,*.somedomain.duckdns.org\"" error="unable to generate a certificate for the domains [somedomain.duckdns.org *.somedomain.duckdns.org]: error: one or more domains had a problem:\n[*.somedomain.duckdns.org] time limit exceeded: last error: could not determine the zone: unexpected response code 'SERVFAIL' for _acme-challenge.somedomain.duckdns.org.\n[somedomain.duckdns.org] time limit exceeded: last error: could not determine authoritative nameservers\n" providerName=myresolver.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=websecure-traefik-traefik-duckdns-letsencrypt@docker rule="Host(`traefik-traefik-duckdns-letsencrypt`)"
```

My only doubt is at `ACME_EMAIL=your-email` should I use my proper email or how it's shown on DuckDNS's dashboard (e.g. `Willdrick@github`). Tried both ways but I can't get it to produce a proper cert.

**Comment by Willdrick** [comment]
nevermid, seems it was a hiccup on DuckDNS's side, didn't do anything and started working with proper certs.
Sorry for this!

**Comment by scafer** [comment]
I'm glad it worked!
It usually takes a while to generate the certificate, but I will try to make this clearer in the documentation.
